# Generated by Django 2.2.12 on 2021-08-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('department', models.IntegerField(verbose_name='ID отдела')),
                ('replaces', models.IntegerField(verbose_name='ID замещаемых работников')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.IntegerField(db_index=True, verbose_name='ID работника')),
                ('start', models.DateField(verbose_name='Начало отпуска')),
                ('end', models.DateField(verbose_name='Конец отпуска')),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуска',
                'ordering': ['id'],
            },
        ),
    ]
