# Generated by Django 2.2.12 on 2022-08-15 10:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('entry_date', models.DateField(default=datetime.date(1, 1, 1), verbose_name='Дата начала работы')),
                ('vacation_days', models.IntegerField(default=38, verbose_name='Дней отпуска')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.Department', verbose_name='Отдел')),
                ('replaces', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacations.Employee', verbose_name='Замещает')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Начало отпуска')),
                ('end', models.DateField(verbose_name='Конец отпуска')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.Employee', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуска',
                'ordering': ['start'],
            },
        ),
    ]
