# Generated by Django 2.2.12 on 2021-08-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-rating'], 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ['employee'], 'verbose_name': 'Отпуск', 'verbose_name_plural': 'Отпуска'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.Department', verbose_name='ID отдела'),
        ),
    ]
