# Generated by Django 2.2.12 on 2021-08-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0005_auto_20210809_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ['start'], 'verbose_name': 'Отпуск', 'verbose_name_plural': 'Отпуска'},
        ),
    ]
