# Generated by Django 2.2.12 on 2021-08-23 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0006_auto_20210817_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='entry_date',
            field=models.DateField(default=datetime.date(1, 1, 1), verbose_name='Дата начала работы'),
        ),
        migrations.AddField(
            model_name='employee',
            name='vacation_days',
            field=models.IntegerField(default=38, verbose_name='Дней отпуска'),
        ),
    ]
