# Generated by Django 2.2.12 on 2021-08-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0007_auto_20210823_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
    ]
